- name: create ec2 instance and r53 configure
  hosts: local
  connection: local
  vars:
    subnet_id: subnet-0b96858c9a92b5ecc # replace with your subnet id
    sg_id: "sg-05c144ada36d13e08"
    ami_id: "ami-09c813fb71547fc4f"
    instances: 
    - mysql
    - backend
    - frontend
  tasks:
  - name: create ec2 instance
    amazon.aws.ec2_instance:
      name: "{{ item }}"
      vpc_subnet_id: "{{ subnet_id }}"
      instance_type: "t2.micro"
      security_group: "{{ sg_id }}"
      image_id: "{{ ami_id }}"
    loop: "{{ instances }}"
    register: ec2_instances

  - name: print the output
    ansible.buitlin.debug:
      msg: "{{ ec2_instances }}"
